services:
  dev:
    image: frontend-dev
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules

  app:
    build:
      context: .
      target: production
    ports:
      - '80:80'
    networks:
      - yatzy

networks:
  yatzy:
    external: true
