name: yatzy-auth

networks:
  default:
    name: yatzy-auth

services:
  auth-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: yatzy_auth
    volumes:
      - auth_db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-uroot', '-proot']
      interval: 1s
      timeout: 5s
      retries: 30

  auth:
    build:
      context: .
      target: prod
    ports:
      - '8001:8001'
    env_file: .env
    depends_on:
      auth-db:
        condition: service_healthy

volumes:
  auth_db_data:
