services:
  auth:
    image: auth-dev
    build:
      context: .
      target: dev
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/app
      - /app/.venv
