SELECT IF(COUNT(*) = 0, 'ALTER TABLE turns ADD COLUMN rolls_used TINYINT UNSIGNED NOT NULL DEFAULT 0', 'SELECT 1') INTO @ddl FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'turns' AND COLUMN_NAME = 'rolls_used';
PREPARE add_rolls_used FROM @ddl;
EXECUTE add_rolls_used;
DEALLOCATE PREPARE add_rolls_used;
