/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description List all players.
         */
        get: operations["list_players_players_get"];
        put?: never;
        /**
         * Create Player
         * @description Create a new player for the authenticated account.
         */
        post: operations["create_player_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Player
         * @description Get the authenticated account's player.
         */
        get: operations["get_my_player_players_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Stats
         * @description Get stats for a player.
         */
        get: operations["get_player_stats_players__player_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player
         * @description Get a player by ID.
         */
        get: operations["get_player_players__player_id__get"];
        /**
         * Update Player
         * @description Update a player's name.
         */
        put: operations["update_player_players__player_id__put"];
        post?: never;
        /**
         * Delete Player
         * @description Delete a player.
         */
        delete: operations["delete_player_players__player_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description List all games, optionally filtered by status.
         */
        get: operations["list_games_games_get"];
        put?: never;
        /**
         * Create Game
         * @description Create a new game. The requesting player becomes the creator.
         */
        post: operations["create_game_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/lobby/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lobby Events
         * @description SSE stream: fires when any lobby-visible game changes.
         */
        get: operations["lobby_events_games_lobby_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/active/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Game Events
         * @description SSE stream: fires when a game the authenticated player participates in changes status.
         */
        get: operations["active_game_events_games_active_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game
         * @description Get a game by ID.
         */
        get: operations["get_game_games__game_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Game
         * @description Delete a game. Only lobby games can be deleted.
         */
        delete: operations["delete_game_games__game_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Leave Game
         * @description Leave a lobby game. The creator cannot leave — delete the game instead.
         */
        delete: operations["leave_game_games__game_id__players__player_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Game
         * @description Join a game that is in the lobby. Up to 6 players can join.
         */
        post: operations["join_game_games__game_id__join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Game
         * @description Start a game. Only the creator can start it.
         */
        post: operations["start_game_games__game_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abort Game
         * @description Abort an active game. The game is marked as abandoned. Only the creator can abort.
         */
        post: operations["abort_game_games__game_id__abort_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/roll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll Dice
         * @description Roll dice for the current player's turn. Pass kept_dice to hold specific dice between rolls.
         */
        post: operations["roll_dice_games__game_id__roll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game State
         * @description Get the current game state. Returns dice, current player and scores when the game has ended.
         */
        get: operations["get_game_state_games__game_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Game Events
         * @description SSE stream: fires when in-game state changes (roll, score, abort).
         */
        get: operations["game_events_games__game_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/players/{player_id}/scorecard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scorecard
         * @description Get the scorecard for a player in a game.
         */
        get: operations["get_scorecard_games__game_id__players__player_id__scorecard_get"];
        /**
         * Score Category
         * @description Score a category with the current dice. Ends the player's turn and advances to the next player. Ends the game when all categories are filled.
         */
        put: operations["score_category_games__game_id__players__player_id__scorecard_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/scoreboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scoreboard
         * @description Get the full scoreboard for all players in a game.
         */
        get: operations["get_scoreboard_games__game_id__scoreboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/players/{player_id}/scoring-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scoring Options
         * @description List scoring categories available for the current dice. In sequential mode, always includes the next required category even if it scores zero. Returns an empty list if no roll has been taken yet this turn.
         */
        get: operations["get_scoring_options_games__game_id__players__player_id__scoring_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/high-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List High Scores
         * @description List all finished games sorted by total score descending.
         */
        get: operations["list_high_scores_high_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games-played-leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games Played
         * @description List top 10 players by number of finished games played, ordered by sort_by.
         */
        get: operations["list_games_played_games_played_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DiceResponse */
        DiceResponse: {
            /**
             * Dice
             * @description All six dice after the roll
             */
            dice: components["schemas"]["Die"][];
        };
        /** Die */
        Die: {
            /**
             * Index
             * @description Die position (0–5)
             */
            index: number;
            /**
             * Value
             * @description Face value (1–6), null if not yet rolled
             */
            value?: number | null;
            /**
             * Kept
             * @description Whether this die is held for the next roll
             */
            kept: boolean;
        };
        /** Game */
        Game: {
            /**
             * Id
             * @description Unique game identifier
             */
            id: number;
            /** @description Current status of the game */
            status: components["schemas"]["GameStatus"];
            /** @description Game mode */
            mode: components["schemas"]["GameMode"];
            /**
             * Creator Id
             * @description ID of the player who created the game
             */
            creator_id: number;
            /**
             * Player Ids
             * @description IDs of all players who have joined
             */
            player_ids: number[];
            /**
             * Created At
             * Format: date-time
             * @description When the game was created
             */
            created_at: string;
            /**
             * Started At
             * @description When the game was started
             */
            started_at?: string | null;
            /**
             * Ended At
             * @description When the game ended
             */
            ended_at?: string | null;
        };
        /** GameCreate */
        GameCreate: {
            /**
             * Creator Id
             * @description ID of the player creating the game
             */
            creator_id: number;
            /**
             * @description Game mode
             * @default maxi
             */
            mode: components["schemas"]["GameMode"];
            /**
             * Bot Count
             * @description Number of bot players to add
             * @default 0
             */
            bot_count: number;
        };
        /** GameJoin */
        GameJoin: {
            /**
             * Player Id
             * @description ID of the player joining the game
             */
            player_id: number;
        };
        /**
         * GameMode
         * @enum {string}
         */
        GameMode: "maxi" | "maxi_sequential" | "yatzy" | "yatzy_sequential";
        /** GameStart */
        GameStart: {
            /**
             * Player Id
             * @description ID of the creator starting the game
             */
            player_id: number;
        };
        /** GameState */
        GameState: {
            /** @description Current game status */
            status: components["schemas"]["GameStatus"];
            /** @description Game mode */
            mode?: components["schemas"]["GameMode"] | null;
            /**
             * Current Player Id
             * @description ID of the player whose turn it is; null when game is not active
             */
            current_player_id?: number | null;
            /**
             * Dice
             * @description Current dice state; null when game is not active
             */
            dice?: components["schemas"]["Die"][] | null;
            /**
             * Rolls Remaining
             * @description Regular rolls left this turn
             */
            rolls_remaining?: number | null;
            /**
             * Saved Rolls
             * @description Saved bonus rolls from previous turns
             */
            saved_rolls?: number | null;
            /**
             * Winner Ids
             * @description IDs of the winner(s); set when game has ended
             */
            winner_ids?: number[] | null;
            /**
             * Final Scores
             * @description Final scores for all players; set when game has ended
             */
            final_scores?: components["schemas"]["PlayerScore"][] | null;
        };
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "lobby" | "active" | "finished" | "abandoned";
        /** GamesPlayed */
        GamesPlayed: {
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name: string;
            /** Total */
            total: number;
            /** Maxi */
            maxi: number;
            /** Maxi Sequential */
            maxi_sequential: number;
            /** Yatzy */
            yatzy: number;
            /** Yatzy Sequential */
            yatzy_sequential: number;
        };
        /**
         * GamesPlayedSortBy
         * @enum {string}
         */
        GamesPlayedSortBy: "total" | "maxi" | "maxi_sequential" | "yatzy" | "yatzy_sequential";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HighScore */
        HighScore: {
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name: string;
            /** Game Id */
            game_id: number;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Total Score */
            total_score: number;
            mode: components["schemas"]["GameMode"];
        };
        /** ModeStats */
        ModeStats: {
            /** Games Played */
            games_played: number;
            /** High Score */
            high_score: number | null;
            /** Average Score */
            average_score: number | null;
            /** Bonus Count */
            bonus_count: number;
            /** Yatzy Hit Count */
            yatzy_hit_count: number;
        };
        /** Player */
        Player: {
            /**
             * Id
             * @description Unique player identifier
             */
            id: number;
            /**
             * Account Id
             * @description Auth account ID that owns this player; null for bot players
             */
            account_id: string | null;
            /**
             * Name
             * @description Display name of the player
             */
            name: string;
            /**
             * Is Bot
             * @description Whether this is an AI bot player
             * @default false
             */
            is_bot: boolean;
            /**
             * Created At
             * Format: date-time
             * @description When the player was created
             */
            created_at: string;
        };
        /** PlayerCreate */
        PlayerCreate: {
            /**
             * Name
             * @description Display name of the player
             */
            name: string;
        };
        /** PlayerScore */
        PlayerScore: {
            /**
             * Player Id
             * @description Player identifier
             */
            player_id: number;
            /**
             * Total
             * @description Final total score including bonus
             */
            total: number;
        };
        /** PlayerScorecard */
        PlayerScorecard: {
            /**
             * Player Id
             * @description Player identifier
             */
            player_id: number;
            /**
             * Entries
             * @description One entry per scoring category
             */
            entries: components["schemas"]["ScoreEntry"][];
            /**
             * Bonus
             * @description Upper section bonus (100 points) if score reaches 84; null if not yet earned
             */
            bonus?: number | null;
            /**
             * Total
             * @description Total score including bonus
             */
            total: number;
        };
        /** PlayerStats */
        PlayerStats: {
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name: string;
            /**
             * Member Since
             * Format: date-time
             */
            member_since: string;
            /** Total Games Played */
            total_games_played: number;
            maxi: components["schemas"]["ModeStats"];
            maxi_sequential: components["schemas"]["ModeStats"];
            yatzy: components["schemas"]["ModeStats"];
            yatzy_sequential: components["schemas"]["ModeStats"];
        };
        /** PlayerUpdate */
        PlayerUpdate: {
            /**
             * Name
             * @description Display name of the player
             */
            name: string;
        };
        /** RollRequest */
        RollRequest: {
            /**
             * Player Id
             * @description ID of the current player
             */
            player_id: number;
            /**
             * Kept Dice
             * @description Indices (0–5) of dice to keep; all others are rerolled
             */
            kept_dice?: number[];
        };
        /**
         * ScoreCategory
         * @enum {string}
         */
        ScoreCategory: "ones" | "twos" | "threes" | "fours" | "fives" | "sixes" | "one_pair" | "two_pairs" | "three_pairs" | "three_of_a_kind" | "four_of_a_kind" | "five_of_a_kind" | "small_straight" | "large_straight" | "full_straight" | "full_house" | "villa" | "tower" | "chance" | "maxi_yatzy" | "yatzy";
        /** ScoreEntry */
        ScoreEntry: {
            /** @description Scoring category */
            category: components["schemas"]["ScoreCategory"];
            /**
             * Score
             * @description Points scored; null if not yet filled
             */
            score?: number | null;
            /**
             * Last Scored
             * @description True if this was the most recently scored category for this player
             * @default false
             */
            last_scored: boolean;
        };
        /** ScoreRequest */
        ScoreRequest: {
            /** @description Category to score with the current dice */
            category: components["schemas"]["ScoreCategory"];
        };
        /** Scorecard */
        Scorecard: {
            /**
             * Entries
             * @description One entry per scoring category
             */
            entries: components["schemas"]["ScoreEntry"][];
            /**
             * Bonus
             * @description Upper section bonus (100 points) if score reaches 84; null if not yet earned
             */
            bonus?: number | null;
            /**
             * Total
             * @description Total score including bonus
             */
            total: number;
        };
        /** ScoringOption */
        ScoringOption: {
            /** @description Available scoring category */
            category: components["schemas"]["ScoreCategory"];
            /**
             * Score
             * @description Points that would be scored for this category with the current dice
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_players_players_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"][];
                };
            };
        };
    };
    create_player_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Player created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Player already exists for this account */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_my_player_players_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No player for this account */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_player_stats_players__player_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStats"];
                };
            };
            /** @description Player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_players__player_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_games_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["GameStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameCreate"];
            };
        };
        responses: {
            /** @description Game created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lobby_events_games_lobby_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    active_game_events_games_active_events_get: {
        parameters: {
            query: {
                player_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_game_games__game_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game cannot be deleted (already started or ended) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leave_game_games__game_id__players__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            /** @description Creator cannot leave the game */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Player not in game or game is not in lobby */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_game_games__game_id__join_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameJoin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game is not in lobby, player already joined, or game is full */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_game_games__game_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game is not in lobby or player is not the creator */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_game_games__game_id__abort_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game is not active */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roll_dice_games__game_id__roll_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiceResponse"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game is not active, not the player's turn, or no rolls remaining */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_state_games__game_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameState"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_events_games__game_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scorecard_games__game_id__players__player_id__scorecard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scorecard"];
                };
            };
            /** @description Game or player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_category_games__game_id__players__player_id__scorecard_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
                player_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scorecard"];
                };
            };
            /** @description Game or player not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the player's turn, no roll taken yet, or category already scored */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoreboard_games__game_id__scoreboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerScorecard"][];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scoring_options_games__game_id__players__player_id__scoring_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoringOption"][];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Game is not active or not the player's turn */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_high_scores_high_scores_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighScore"][];
                };
            };
        };
    };
    list_games_played_games_played_leaderboard_get: {
        parameters: {
            query?: {
                sort_by?: components["schemas"]["GamesPlayedSortBy"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GamesPlayed"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
