name: yatzy-cli

networks:
  yatzy_default:
    external: true

services:
  cli:
    build:
      context: .
      target: prod
    stdin_open: true
    tty: true
    networks:
      - yatzy_default
    volumes:
      - ${HOME}/.yatzy:/root/.yatzy
    environment:
      - AUTH_URL=http://auth:8001
      - BACKEND_URL=http://backend:8000

  cli-dev:
    build:
      context: .
      target: dev
    stdin_open: true
    tty: true
    networks:
      - yatzy_default
    volumes:
      - .:/app
      - ${HOME}/.yatzy:/root/.yatzy
    environment:
      - AUTH_URL=http://auth:8001
      - BACKEND_URL=http://backend:8000
    command: python main.py
