name: yatzy-bot

services:
  bot:
    build:
      context: ..
      dockerfile: bot/Dockerfile
      target: dev
    environment:
      - PYTHONPATH=/bot
      - UV_LINK_MODE=copy
    volumes:
      - .:/bot
      - /bot/.venv
      - ../shared:/shared
    ports:
      - '8002:8002'
    command: ['uv', 'run', 'uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8002', '--reload']
