name: Auth CI

on:
  push:
    branches: ['**']
    paths:
      - 'auth/**'
      - '.github/workflows/auth.yml'
  pull_request:
    branches: ['**']
    paths:
      - 'auth/**'
      - '.github/workflows/auth.yml'

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/package-ci.yml
    with:
      package: auth
      check_targets: '{"target":["lint-dockerfile","lint","types","security"]}'
    secrets: inherit
