name: Bot CI

on:
  push:
    branches: ['**']
    paths:
      - 'bot/**'
      - 'yatzy_rules/**'
      - '.github/workflows/bot.yml'
  pull_request:
    branches: ['**']
    paths:
      - 'bot/**'
      - 'yatzy_rules/**'
      - '.github/workflows/bot.yml'

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/package-ci.yml
    with:
      package: bot
      check_targets: '{"target":["lint-dockerfile","lint","types"]}'
    secrets: inherit
