name: E2E CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: sirmar/dev@main
      - run: mdev build backend auth frontend e2e
      - run: cd e2e && dev run
