name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: backend
          target: prod
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:backend-${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:backend-latest
          cache-from: type=gha,scope=backend-dev
          cache-to: type=gha,mode=max,scope=backend-prod

  auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: auth
          target: prod
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:auth-${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:auth-latest
          cache-from: type=gha,scope=auth-dev
          cache-to: type=gha,mode=max,scope=auth-prod

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: frontend
          target: production
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:frontend-${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:frontend-latest
          cache-from: type=gha,scope=frontend-dev
          cache-to: type=gha,mode=max,scope=frontend-prod
