name: Yatzy Rules CI

on:
  push:
    branches: ['**']
    paths:
      - 'yatzy_rules/**'
      - '.github/workflows/yatzy_rules.yml'
  pull_request:
    branches: ['**']
    paths:
      - 'yatzy_rules/**'
      - '.github/workflows/yatzy_rules.yml'

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/package-ci.yml
    with:
      package: yatzy_rules
      check_targets: '{"target":["lint","types","security"]}'
    secrets: inherit
